/* Krave Kulture: generates JSON-LD structured data from menu-data.js and injects
 * it between the <!-- SCHEMA:START --> / <!-- SCHEMA:END --> markers in
 * site/index.html and site/menu.html. Re-run this any time menu-data.js changes.
 *
 * Usage: node make-schema.js
 *
 * Only reads real data already in menu-data.js: no invented address, phone,
 * hours, reviews or payment methods. The truck has no fixed address, so this
 * uses areaServed instead of a street address, and sameAs points at Instagram
 * instead of a phone number.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = __dirname;
const SITE_URL = "https://kravekulture.vercel.app";

function loadMenuData() {
  const src = fs.readFileSync(path.join(ROOT, "site/menu-data.js"), "utf8");
  const sandbox = {};
  vm.createContext(sandbox);
  vm.runInContext(src + "\nthis.MENU=MENU;this.PAYMENTS=PAYMENTS;this.LOCATION=LOCATION;this.MENU_STATUS=MENU_STATUS;", sandbox);
  return { MENU: sandbox.MENU, LOCATION: sandbox.LOCATION };
}

const items = (section) => section.items || [];

function priceRange(MENU) {
  const prices = [];
  MENU.forEach((s) => items(s).forEach((i) => { if (typeof i.price === "number") prices.push(i.price); }));
  if (!prices.length) return undefined;
  return `$${Math.min(...prices)}-$${Math.max(...prices)}`;
}

// One business entity, identical on every page (same @id / url / image list), so
// search engines see one FoodEstablishment rather than two look-alikes.
function foodEstablishment(MENU, LOCATION) {
  // LOCATION.city is "Miami, FL". Google's LocalBusiness guidance requires a
  // PostalAddress; for a truck with no fixed street, city/region/country is the
  // honest minimum (no invented street, no invented hours).
  const [locality, region] = String(LOCATION.city).split(",").map((s) => s.trim());
  return {
    "@context": "https://schema.org",
    "@type": "FoodEstablishment",
    "@id": `${SITE_URL}/#business`,
    name: "Krave Kulture",
    url: `${SITE_URL}/`,
    image: [`${SITE_URL}/images/og-home.jpg`, `${SITE_URL}/world/truck.webp`, `${SITE_URL}/images/logo-512.png`],
    description: "Haitian, Caribbean and soul food truck serving Miami, FL.",
    servesCuisine: ["Haitian", "Caribbean", "Soul food"],
    address: { "@type": "PostalAddress", addressLocality: locality, addressRegion: region || undefined, addressCountry: "US" },
    areaServed: { "@type": "City", name: LOCATION.city },
    sameAs: [LOCATION.instagram],
    priceRange: priceRange(MENU),
    menu: `${SITE_URL}/menu.html`,
  };
}

function menuSchema(MENU) {
  return {
    "@context": "https://schema.org",
    "@type": "Menu",
    name: "Krave Kulture Menu",
    hasMenuSection: MENU.filter((section) => items(section).length).map((section) => ({
      "@type": "MenuSection",
      name: section.title,
      description: section.note || undefined,
      hasMenuItem: items(section).map((item) => {
        const menuItem = {
          "@type": "MenuItem",
          name: item.name,
        };
        if (item.desc) menuItem.description = item.desc;
        if (typeof item.price === "number") {
          menuItem.offers = {
            "@type": "Offer",
            price: String(item.price),
            priceCurrency: "USD",
          };
        }
        return menuItem;
      }),
    })),
  };
}

function inject(file, blocks) {
  const p = path.join(ROOT, file);
  let html = fs.readFileSync(p, "utf8");
  const start = "<!-- SCHEMA:START (generated by make-schema.js from menu-data.js — do not hand-edit) -->";
  const end = "<!-- SCHEMA:END -->";
  const si = html.indexOf(start), ei = html.indexOf(end);
  if (si === -1 || ei === -1) throw new Error(`${file}: SCHEMA markers not found`);
  const scripts = blocks
    .map((b) => `  <script type="application/ld+json">\n${JSON.stringify(b, null, 2)}\n  </script>`)
    .join("\n");
  const next = html.slice(0, si + start.length) + "\n" + scripts + "\n  " + html.slice(ei);
  fs.writeFileSync(p, next);
  console.log(`Wrote ${blocks.length} JSON-LD block(s) into ${file}`);
}

const { MENU, LOCATION } = loadMenuData();

inject("site/index.html", [foodEstablishment(MENU, LOCATION)]);

inject("site/menu.html", [foodEstablishment(MENU, LOCATION), menuSchema(MENU)]);
